# Generated by Django 5.2.18 on 2026-10-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabana',
            options={},
        ),
        migrations.RenameField(
            model_name='cabana',
            old_name='cantidad_personas',
            new_name='capacidad',
        ),
    ]
