# Generated by Django 5.2.18 on 2026-10-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alojamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("ubicacion", models.CharField(max_length=200)),
                ("precio_noche", models.DecimalField(decimal_places=2, max_digits=10)),
                ("disponible", models.BooleanField(default=True)),
            ],
        ),
    ]
