# Generated by Django 5.2.18 on 2026-10-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos_apps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alojamiento',
        ),
    ]
