# Generated by Django 5.2.18 on 2026-10-08 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cabanas", "0001_initial"),
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_ingreso", models.DateField()),
                ("hora_ingreso", models.TimeField()),
                ("fecha_salida", models.DateField()),
                ("hora_salida", models.TimeField()),
                (
                    "cabana",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cabanas.cabana"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
            },
        ),
    ]
