# Generated by Django 6.1.1 on 2026-09-29 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0001_initial'),
        ('clientes', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alquiler',
            new_name='Reserva',
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
    ]
